---

- hosts: webservers
  become: true
  tasks:

  - name: install apache and php packages for Debian
    tags: debian, apache, php
    apt:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
