---

- hosts: webservers
  become: true
  tasks:

  - name: install apache and php packages for Debian
    tags: debian, apache, php
    apt:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

  - name: copy file
    tags: apache, debian
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: create simone user
    tags: always
    user:
      name: simone
      groups: root
